-- 广告系统数据表结构

-- 广告位表
CREATE TABLE IF NOT EXISTS `ad_positions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT '广告位名称',
  `code` VARCHAR(64) NOT NULL COMMENT '广告位编码',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '广告位描述',
  `type` VARCHAR(32) NOT NULL COMMENT '广告位类型：banner-横幅 popup-弹窗 float-悬浮 embed-嵌入 video-视频',
  `template` VARCHAR(255) DEFAULT NULL COMMENT '广告位模板',
  `size` VARCHAR(64) DEFAULT NULL COMMENT '广告位尺寸，格式：宽x高，如：300x250',
  `max_ads` INT DEFAULT 1 COMMENT '最大广告数量',
  `page_type` VARCHAR(64) DEFAULT NULL COMMENT '页面类型：home-首页 list-列表页 detail-详情页 search-搜索页 etc.',
  `device` VARCHAR(32) DEFAULT 'all' COMMENT '设备类型：all-全部 pc-电脑 mobile-手机 tablet-平板',
  `status` INT DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
  `sort_order` INT DEFAULT 0 COMMENT '排序顺序',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID，为NULL表示系统广告位',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_code_tenant` (`code`, `tenant_id`),
  KEY `idx_type` (`type`),
  KEY `idx_page_type` (`page_type`),
  KEY `idx_device` (`device`),
  KEY `idx_status` (`status`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告位表';

-- 广告表
CREATE TABLE IF NOT EXISTS `advertisements` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL COMMENT '广告标题',
  `description` VARCHAR(512) DEFAULT NULL COMMENT '广告描述',
  `position_id` BIGINT NOT NULL COMMENT '广告位ID',
  `type` VARCHAR(32) DEFAULT 'image' COMMENT '广告类型：image-图片 text-文字 video-视频 code-代码',
  `content` TEXT NOT NULL COMMENT '广告内容：图片URL、文字、视频URL或HTML代码',
  `link_url` VARCHAR(512) DEFAULT NULL COMMENT '广告链接',
  `link_type` VARCHAR(32) DEFAULT '_blank' COMMENT '链接打开方式：_blank-新窗口 _self-当前窗口',
  `start_time` TIMESTAMP NULL COMMENT '开始时间',
  `end_time` TIMESTAMP NULL COMMENT '结束时间',
  `priority` INT DEFAULT 0 COMMENT '优先级，数字越大优先级越高',
  `price` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '广告价格',
  `daily_budget` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '日预算',
  `total_budget` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '总预算',
  `target_audience` JSON DEFAULT NULL COMMENT '目标受众(JSON格式)',
  `keywords` VARCHAR(512) DEFAULT NULL COMMENT '关键词，多个用逗号分隔',
  `status` INT DEFAULT 1 COMMENT '状态：0-禁用 1-启用 2-待审核 3-已过期 4-预定',
  `advertiser_id` BIGINT DEFAULT NULL COMMENT '广告主ID',
  `advertiser_name` VARCHAR(128) DEFAULT NULL COMMENT '广告主名称',
  `contact_name` VARCHAR(64) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  `contact_email` VARCHAR(128) DEFAULT NULL COMMENT '联系邮箱',
  `approve_status` INT DEFAULT 0 COMMENT '审核状态：0-待审核 1-审核通过 2-审核拒绝',
  `approve_time` TIMESTAMP NULL COMMENT '审核时间',
  `approver_id` BIGINT DEFAULT NULL COMMENT '审核人ID',
  `approve_comment` VARCHAR(255) DEFAULT NULL COMMENT '审核意见',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_position_id` (`position_id`),
  KEY `idx_status` (`status`),
  KEY `idx_approve_status` (`approve_status`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_end_time` (`end_time`),
  KEY `idx_advertiser_id` (`advertiser_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  CONSTRAINT `fk_advertisements_position_id` FOREIGN KEY (`position_id`) REFERENCES `ad_positions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告表';

-- 广告展示记录表
CREATE TABLE IF NOT EXISTS `ad_impressions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ad_id` BIGINT NOT NULL COMMENT '广告ID',
  `position_id` BIGINT NOT NULL COMMENT '广告位ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户ID，为NULL表示未登录用户',
  `ip` VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  `user_agent` VARCHAR(512) DEFAULT NULL COMMENT '用户代理',
  `referer` VARCHAR(512) DEFAULT NULL COMMENT '来源URL',
  `page_url` VARCHAR(512) DEFAULT NULL COMMENT '页面URL',
  `device_type` VARCHAR(32) DEFAULT NULL COMMENT '设备类型：pc, mobile, tablet',
  `impression_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '展示时间',
  `country` VARCHAR(64) DEFAULT NULL COMMENT '国家',
  `region` VARCHAR(64) DEFAULT NULL COMMENT '地区',
  `city` VARCHAR(64) DEFAULT NULL COMMENT '城市',
  `cost` DECIMAL(10, 6) DEFAULT 0 COMMENT '展示成本',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  KEY `idx_ad_id` (`ad_id`),
  KEY `idx_position_id` (`position_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_impression_time` (`impression_time`),
  KEY `idx_tenant_id` (`tenant_id`),
  CONSTRAINT `fk_ad_impressions_ad_id` FOREIGN KEY (`ad_id`) REFERENCES `advertisements` (`id`),
  CONSTRAINT `fk_ad_impressions_position_id` FOREIGN KEY (`position_id`) REFERENCES `ad_positions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告展示记录表';

-- 广告点击记录表
CREATE TABLE IF NOT EXISTS `ad_clicks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ad_id` BIGINT NOT NULL COMMENT '广告ID',
  `position_id` BIGINT NOT NULL COMMENT '广告位ID',
  `impression_id` BIGINT DEFAULT NULL COMMENT '展示记录ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户ID，为NULL表示未登录用户',
  `ip` VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  `user_agent` VARCHAR(512) DEFAULT NULL COMMENT '用户代理',
  `referer` VARCHAR(512) DEFAULT NULL COMMENT '来源URL',
  `landing_page` VARCHAR(512) DEFAULT NULL COMMENT '落地页URL',
  `device_type` VARCHAR(32) DEFAULT NULL COMMENT '设备类型：pc, mobile, tablet',
  `click_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '点击时间',
  `country` VARCHAR(64) DEFAULT NULL COMMENT '国家',
  `region` VARCHAR(64) DEFAULT NULL COMMENT '地区',
  `city` VARCHAR(64) DEFAULT NULL COMMENT '城市',
  `cost` DECIMAL(10, 6) DEFAULT 0 COMMENT '点击成本',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  KEY `idx_ad_id` (`ad_id`),
  KEY `idx_position_id` (`position_id`),
  KEY `idx_impression_id` (`impression_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_click_time` (`click_time`),
  KEY `idx_tenant_id` (`tenant_id`),
  CONSTRAINT `fk_ad_clicks_ad_id` FOREIGN KEY (`ad_id`) REFERENCES `advertisements` (`id`),
  CONSTRAINT `fk_ad_clicks_position_id` FOREIGN KEY (`position_id`) REFERENCES `ad_positions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告点击记录表';

-- 广告统计表
CREATE TABLE IF NOT EXISTS `ad_statistics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ad_id` BIGINT NOT NULL COMMENT '广告ID',
  `position_id` BIGINT NOT NULL COMMENT '广告位ID',
  `date` DATE NOT NULL COMMENT '统计日期',
  `impressions` INT DEFAULT 0 COMMENT '展示次数',
  `clicks` INT DEFAULT 0 COMMENT '点击次数',
  `unique_impressions` INT DEFAULT 0 COMMENT '独立展示次数',
  `unique_clicks` INT DEFAULT 0 COMMENT '独立点击次数',
  `ctr` DECIMAL(10, 6) DEFAULT 0 COMMENT '点击率',
  `cost` DECIMAL(10, 2) DEFAULT 0 COMMENT '总成本',
  `conversions` INT DEFAULT 0 COMMENT '转化次数',
  `conversion_rate` DECIMAL(10, 6) DEFAULT 0 COMMENT '转化率',
  `revenue` DECIMAL(10, 2) DEFAULT 0 COMMENT '收入',
  `roi` DECIMAL(10, 6) DEFAULT 0 COMMENT '投资回报率',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_ad_position_date` (`ad_id`, `position_id`, `date`),
  KEY `idx_ad_id` (`ad_id`),
  KEY `idx_position_id` (`position_id`),
  KEY `idx_date` (`date`),
  KEY `idx_tenant_id` (`tenant_id`),
  CONSTRAINT `fk_ad_statistics_ad_id` FOREIGN KEY (`ad_id`) REFERENCES `advertisements` (`id`),
  CONSTRAINT `fk_ad_statistics_position_id` FOREIGN KEY (`position_id`) REFERENCES `ad_positions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告统计表';

-- 广告主表
CREATE TABLE IF NOT EXISTS `advertisers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT '广告主名称',
  `code` VARCHAR(64) NOT NULL COMMENT '广告主编码',
  `description` VARCHAR(512) DEFAULT NULL COMMENT '广告主描述',
  `contact_name` VARCHAR(64) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  `contact_email` VARCHAR(128) DEFAULT NULL COMMENT '联系邮箱',
  `address` VARCHAR(255) DEFAULT NULL COMMENT '地址',
  `website` VARCHAR(255) DEFAULT NULL COMMENT '网站',
  `industry` VARCHAR(64) DEFAULT NULL COMMENT '行业',
  `logo` VARCHAR(255) DEFAULT NULL COMMENT 'Logo',
  `balance` DECIMAL(12, 2) DEFAULT 0.00 COMMENT '账户余额',
  `credit_limit` DECIMAL(12, 2) DEFAULT 0.00 COMMENT '信用额度',
  `status` INT DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
  `user_id` BIGINT DEFAULT NULL COMMENT '关联用户ID',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_code` (`code`),
  KEY `idx_name` (`name`),
  KEY `idx_status` (`status`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告主表';

-- 广告计划表
CREATE TABLE IF NOT EXISTS `ad_campaigns` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT '计划名称',
  `advertiser_id` BIGINT NOT NULL COMMENT '广告主ID',
  `description` VARCHAR(512) DEFAULT NULL COMMENT '计划描述',
  `start_time` TIMESTAMP NULL COMMENT '开始时间',
  `end_time` TIMESTAMP NULL COMMENT '结束时间',
  `daily_budget` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '日预算',
  `total_budget` DECIMAL(10, 2) DEFAULT 0.00 COMMENT '总预算',
  `bid_type` VARCHAR(32) DEFAULT 'cpc' COMMENT '出价类型：cpc-点击 cpm-展示 cpa-行动',
  `bid_amount` DECIMAL(10, 6) DEFAULT 0 COMMENT '出价金额',
  `target_audience` JSON DEFAULT NULL COMMENT '目标受众(JSON格式)',
  `schedule` JSON DEFAULT NULL COMMENT '投放时间表(JSON格式)',
  `device_targeting` JSON DEFAULT NULL COMMENT '设备定向(JSON格式)',
  `geo_targeting` JSON DEFAULT NULL COMMENT '地域定向(JSON格式)',
  `status` INT DEFAULT 1 COMMENT '状态：0-暂停 1-运行 2-结束 3-草稿',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_advertiser_id` (`advertiser_id`),
  KEY `idx_status` (`status`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_end_time` (`end_time`),
  KEY `idx_tenant_id` (`tenant_id`),
  CONSTRAINT `fk_ad_campaigns_advertiser_id` FOREIGN KEY (`advertiser_id`) REFERENCES `advertisers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告计划表';

-- 广告素材表
CREATE TABLE IF NOT EXISTS `ad_materials` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT '素材名称',
  `advertiser_id` BIGINT NOT NULL COMMENT '广告主ID',
  `type` VARCHAR(32) NOT NULL COMMENT '素材类型：image-图片 video-视频 text-文字 html-HTML',
  `content` TEXT NOT NULL COMMENT '素材内容：图片URL、视频URL、文字内容或HTML代码',
  `size` VARCHAR(64) DEFAULT NULL COMMENT '素材尺寸，格式：宽x高，如：300x250',
  `duration` INT DEFAULT NULL COMMENT '素材时长(秒)，适用于视频素材',
  `file_size` INT DEFAULT NULL COMMENT '文件大小(KB)',
  `file_type` VARCHAR(32) DEFAULT NULL COMMENT '文件类型：jpg, png, mp4, etc.',
  `preview_url` VARCHAR(255) DEFAULT NULL COMMENT '预览URL',
  `status` INT DEFAULT 1 COMMENT '状态：0-禁用 1-启用 2-待审核 3-审核拒绝',
  `approve_status` INT DEFAULT 0 COMMENT '审核状态：0-待审核 1-审核通过 2-审核拒绝',
  `approve_time` TIMESTAMP NULL COMMENT '审核时间',
  `approver_id` BIGINT DEFAULT NULL COMMENT '审核人ID',
  `approve_comment` VARCHAR(255) DEFAULT NULL COMMENT '审核意见',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_advertiser_id` (`advertiser_id`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`),
  KEY `idx_approve_status` (`approve_status`),
  KEY `idx_tenant_id` (`tenant_id`),
  CONSTRAINT `fk_ad_materials_advertiser_id` FOREIGN KEY (`advertiser_id`) REFERENCES `advertisers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广告素材表';

-- 初始化基础广告位
INSERT INTO `ad_positions` (`name`, `code`, `description`, `type`, `size`, `page_type`, `status`) VALUES
('首页轮播图', 'home-banner', '首页顶部轮播广告位', 'banner', '1200x400', 'home', 1),
('内容页侧栏', 'content-sidebar', '内容页右侧广告位', 'embed', '300x250', 'detail', 1),
('搜索结果页顶部', 'search-top', '搜索结果页顶部广告位', 'banner', '970x90', 'search', 1),
('文章底部推荐', 'article-bottom', '文章底部推荐广告位', 'embed', '728x90', 'detail', 1),
('弹窗广告', 'popup-ad', '全站弹窗广告', 'popup', '600x400', 'all', 1);
