// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

// 这是一个 protobuf 生成文件的存根
// 实际项目中，应该使用 protoc 命令生成完整的文件
// 例如: protoc --go_out=. --go-grpc_out=. user.proto

// UserServer 是 User 服务的服务器 API
type UserServer interface {
	// 用户注册
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 用户登录
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// 获取用户信息
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// 更新用户信息
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// 验证用户
	VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error)
	// 企业认证
	VerifyCompany(context.Context, *VerifyCompanyRequest) (*VerifyCompanyResponse, error)
	// 获取用户行为分析
	GetUserBehavior(context.Context, *GetUserBehaviorRequest) (*GetUserBehaviorResponse, error)
}

// UnimplementedUserServer 可以被嵌入到没有实现的服务器中
type UnimplementedUserServer struct{}

// 简化的请求和响应类型定义
type RegisterRequest struct{}
type RegisterResponse struct{}
type LoginRequest struct{}
type LoginResponse struct{}
type GetUserRequest struct{}
type GetUserResponse struct{}
type UpdateUserRequest struct{}
type UpdateUserResponse struct{}
type VerifyUserRequest struct{}
type VerifyUserResponse struct{}
type VerifyCompanyRequest struct{}
type VerifyCompanyResponse struct{}
type GetUserBehaviorRequest struct{}
type GetUserBehaviorResponse struct{}
type UserBehavior struct{}

// RegisterUserServer 注册 User 服务到 gRPC 服务器
func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// 实际生成的代码应该实现此函数
} 