// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: file.proto

package server

import (
	"context"

	"wz-backend-go/api/rpc/file"
	"wz-backend-go/internal/delivery/rpc/internal/logic"
	"wz-backend-go/internal/delivery/rpc/internal/svc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

// 上传文件
func (s *FileServer) Upload(ctx context.Context, in *file.UploadRequest) (*file.UploadResponse, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

// 获取文件信息
func (s *FileServer) GetFile(ctx context.Context, in *file.GetFileRequest) (*file.GetFileResponse, error) {
	l := logic.NewGetFileLogic(ctx, s.svcCtx)
	return l.GetFile(in)
}

// 删除文件
func (s *FileServer) DeleteFile(ctx context.Context, in *file.DeleteFileRequest) (*file.DeleteFileResponse, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}

// 获取文件列表
func (s *FileServer) ListFiles(ctx context.Context, in *file.ListFilesRequest) (*file.ListFilesResponse, error) {
	l := logic.NewListFilesLogic(ctx, s.svcCtx)
	return l.ListFiles(in)
}
