Name: content-api
Host: 0.0.0.0
Port: 8001
Mode: dev

Log:
  ServiceName: content-api
  Level: info

DB:
  DataSource: root:password@tcp(localhost:3306)/wz_backend?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

Auth:
  AccessSecret: your-access-secret-key-for-jwt-token
  AccessExpire: 86400  # 24 hours

ContentRpc:
  Etcd:
    Hosts:
      - localhost:2379
    Key: content.rpc
