Name: file-api
Host: 0.0.0.0
Port: 8887

# 数据库配置
DB:
  DataSource: root:123456@tcp(127.0.0.1:3306)/wz_file?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

# Redis配置
Redis:
  Host: 127.0.0.1:6379
  Pass: ""
  Type: node

# JWT配置
Auth:
  AccessSecret: your-secret-key
  AccessExpire: 86400

# 文件存储配置
Storage:
  # 本地存储配置
  Local:
    RootDir: ./storage
    MaxSize: 10485760 # 10MB
    AllowedTypes: ["image/jpeg", "image/png", "image/gif", "video/mp4"]
  
  # 对象存储配置
  Object:
    Provider: minio
    Endpoint: play.min.io
    AccessKey: your-access-key
    SecretKey: your-secret-key
    Bucket: wz-files
    Region: us-east-1
    Secure: true

# 日志配置
Log:
  ServiceName: file-api
  Mode: console
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05.000
  Stat: false
  Level: info
  Compress: false
  KeepDays: 7
  StackCooldownMillis: 100 